### PR TITLE
Live visualization

### PR DESCRIPTION
**Pull request by jacione**
Potential solution to issue #10.
 
I added `live_operation()` to `Rec` and `CoupledRec`, which allows the reconstruction progress to be viewed in real time. For single-peak BCDI, it shows the amplitude, phase, and support, along with a plot of the error. For multipeak, the error/support panels are replaced by the diffraction pattern currently in rotation, before and after alien removal. The diffraction patterns are _not_ central slices but are instead summed along one axis (this allows aliens to show up despite not being centered).

The corresponding `live_trigger` goes in config_rec and follows standard trigger notation. The documentation has been updated to include this. The trigger is activated immediately after `progress_trigger`.

P.S. I don't know why this also included all of the commit history from my last PR (#32).

### CODE REVIEW

**Comment by brussel13** [comment]
There is also a trame interface being developed by one of the SDM group members.


________________________________
From: Nick Porter ***@***.***>
Sent: Thursday, October 24, 2024 10:42 PM
To: AdvancedPhotonSource/cohere ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AdvancedPhotonSource/cohere] Live visualization (PR #35)

Potential solution to issue #10.   I added live_operation() to Rec and CoupledRec, which allows the reconstruction progress to be viewed in real time. For single-peak BCDI, it shows the amplitude, phase, and support, along with a plot of the
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

Potential solution to issue #10<https://urldefense.us/v3/__https://github.com/AdvancedPhotonSource/cohere/issues/10__;!!G_uCfscf7eWS!d_iLb1-fcMLjpdmqvCaiyGKhL9H2J14G3eWpiTBg6NAbK1mLqqOKgjpnPKizC1gtPDcjxNcEh_2q0AbluYf6XnMCow$>.

I added live_operation() to Rec and CoupledRec, which allows the reconstruction progress to be viewed in real time. For single-peak BCDI, it shows the amplitude, phase, and support, along with a plot of the error. For multipeak, the error/support panels are replaced by the diffraction pattern currently in rotation, before and after alien removal. The diffraction patterns are not central slices but are instead summed along one axis (this allows aliens to show up despite not being centered).

The corresponding live_trigger goes in config_rec and follows standard trigger notation. The documentation has been updated to include this.

P.S. I don't know why this also included all of the commit history from my last PR (#32<https://urldefense.us/v3/__https://github.com/AdvancedPhotonSource/cohere/pull/32__;!!G_uCfscf7eWS!d_iLb1-fcMLjpdmqvCaiyGKhL9H2J14G3eWpiTBg6NAbK1mLqqOKgjpnPKizC1gtPDcjxNcEh_2q0AbluYeaNJgtWA$>).

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/AdvancedPhotonSource/cohere/pull/35<https://urldefense.us/v3/__https://github.com/AdvancedPhotonSource/cohere/pull/35__;!!G_uCfscf7eWS!d_iLb1-fcMLjpdmqvCaiyGKhL9H2J14G3eWpiTBg6NAbK1mLqqOKgjpnPKizC1gtPDcjxNcEh_2q0AbluYcNt5fX7A$>

Commit Summary

  *   86c97a9<https://urldefense.us/v3/__https://github.com/AdvancedPhotonSource/cohere/pull/35/commits/86c97a982858279a4639036f31fb6dc628bbfc9b__;!!G_uCfscf7eWS!d_iLb1-fcMLjpdmqvCaiyGKhL9H2J14G3eWpiTBg6NAbK1mLqqOKgjpnPKizC1gtPDcjxNcEh_2q0AbluYcC_if0ng$> Fixed a few bugs in multipeak phasing
  *   5302b4a<https://urldefense.us/v3/__https://github.com/AdvancedPhotonSource/cohere/pull/35/commits/5302b4a1fb9c4d5d8cd78330d38b540bab34e8e6__;!!G_uCfscf7eWS!d_iLb1-fcMLjpdmqvCaiyGKhL9H2J14G3eWpiTBg6NAbK1mLqqOKgjpnPKizC1gtPDcjxNcEh_2q0AbluYc_gGVftw$> Adaptive alien removal for multipeak
  *   1793c1d<https://urldefense.us/v3/__https://github.com/AdvancedPhotonSource/cohere/pull/35/commits/1793c1db5154d87a29105334e126d4b3edb9b48e__;!!G_uCfscf7eWS!d_iLb1-fcMLjpdmqvCaiyGKhL9H2J14G3eWpiTBg6NAbK1mLqqOKgjpnPKizC1gtPDcjxNcEh_2q0AbluYenfB-Y4A$> Moved live viewing to its own CoupledRec method so that iterate() isn't so crowded.
  *   536676b<https://urldefense.us/v3/__https://github.com/AdvancedPhotonSource/cohere/pull/35/commits/536676b07d285850c555a91ada7a74ad75e447b7__;!!G_uCfscf7eWS!d_iLb1-fcMLjpdmqvCaiyGKhL9H2J14G3eWpiTBg6NAbK1mLqqOKgjpnPKizC1gtPDcjxNcEh_2q0AbluYdeuJwg6Q$> Added a bunch of comments for multipeak stuff
  *   45ea125<https://urldefense.us/v3/__https://github.com/AdvancedPhotonSource/cohere/pull/35/commits/45ea125fcf9cf1f0c14f473930a66856ea6268b0__;!!G_uCfscf7eWS!d_iLb1-fcMLjpdmqvCaiyGKhL9H2J14G3eWpiTBg6NAbK1mLqqOKgjpnPKizC1gtPDcjxNcEh_2q0AbluYcMljeS7g$> Adds feedback from the shared object when applying the Fourier constraint. The amount of feedback depends on that peak's confidence value.
  *   4494e64<https://urldefense.us/v3/__https://github.com/AdvancedPhotonSource/cohere/pull/35/commits/4494e64b1c275bfbf9e9f20d56bd8637ad278f54__;!!G_uCfscf7eWS!d_iLb1-fcMLjpdmqvCaiyGKhL9H2J14G3eWpiTBg6NAbK1mLqqOKgjpnPKizC1gtPDcjxNcEh_2q0AbluYdIdkVG9A$> Updated parameters in config_mp:
  *   c7e2a40<https://urldefense.us/v3/__https://github.com/AdvancedPhotonSource/cohere/pull/35/commits/c7e2a408b965bc1107c81832cbea89db468c8b24__;!!G_uCfscf7eWS!d_iLb1-fcMLjpdmqvCaiyGKhL9H2J14G3eWpiTBg6NAbK1mLqqOKgjpnPKizC1gtPDcjxNcEh_2q0AbluYdpjBRNGQ$> Updated documentation for multipeak configuration
  *   d061ab1<https://urldefense.us/v3/__https://github.com/AdvancedPhotonSource/cohere/pull/35/commits/d061ab140474c258dcf257bdac91aa05802be70d__;!!G_uCfscf7eWS!d_iLb1-fcMLjpdmqvCaiyGKhL9H2J14G3eWpiTBg6NAbK1mLqqOKgjpnPKizC1gtPDcjxNcEh_2q0AbluYdfLLg-5w$> Added live display trigger for both single and multipeak.
  *   355c55d<https://urldefense.us/v3/__https://github.com/AdvancedPhotonSource/cohere/pull/35/commits/355c55d746dd98172e87365d542089926be85766__;!!G_uCfscf7eWS!d_iLb1-fcMLjpdmqvCaiyGKhL9H2J14G3eWpiTBg6NAbK1mLqqOKgjpnPKizC1gtPDcjxNcEh_2q0AbluYd-CQeFpw$> Merge remote-tracking branch 'origin/Dev' into Dev
  *   0227b8f<https://urldefense.us/v3/__https://github.com/AdvancedPhotonSource/cohere/pull/35/commits/0227b8f5d77a57c198dfda3a9440c7d60416054f__;!!G_uCfscf7eWS!d_iLb1-fcMLjpdmqvCaiyGKhL9H2J14G3eWpiTBg6NAbK1mLqqOKgjpnPKizC1gtPDcjxNcEh_2q0AbluYeMmgCLDA$> Fixed colorscales on multipeak live visualization to match single-peak

File Changes

(2 files<https://urldefense.us/v3/__https://github.com/AdvancedPhotonSource/cohere/pull/35/files__;!!G_uCfscf7eWS!d_iLb1-fcMLjpdmqvCaiyGKhL9H2J14G3eWpiTBg6NAbK1mLqqOKgjpnPKizC1gtPDcjxNcEh_2q0AbluYdyv4xY1g$>)

  *   M cohere_core/controller/phasing.py<https://urldefense.us/v3/__https://github.com/AdvancedPhotonSource/cohere/pull/35/files*diff-d9056267f3e18b54a6428382606e3eb4414310bf26c2c94259368a41aefbc534__;Iw!!G_uCfscf7eWS!d_iLb1-fcMLjpdmqvCaiyGKhL9H2J14G3eWpiTBg6NAbK1mLqqOKgjpnPKizC1gtPDcjxNcEh_2q0AbluYcGZSJgyg$> (74)
  *   M docs/source/config_rec.rst<https://urldefense.us/v3/__https://github.com/AdvancedPhotonSource/cohere/pull/35/files*diff-2c2e647ebb9573e83fee88bf8dc4d8c6f4fcc689c44f97bbbb634cc51d728511__;Iw!!G_uCfscf7eWS!d_iLb1-fcMLjpdmqvCaiyGKhL9H2J14G3eWpiTBg6NAbK1mLqqOKgjpnPKizC1gtPDcjxNcEh_2q0AbluYeLJabJ4A$> (10)

Patch Links:

  *   https://github.com/AdvancedPhotonSource/cohere/pull/35.patch<https://urldefense.us/v3/__https://github.com/AdvancedPhotonSource/cohere/pull/35.patch__;!!G_uCfscf7eWS!d_iLb1-fcMLjpdmqvCaiyGKhL9H2J14G3eWpiTBg6NAbK1mLqqOKgjpnPKizC1gtPDcjxNcEh_2q0AbluYfBVHTQJw$>
  *   https://github.com/AdvancedPhotonSource/cohere/pull/35.diff<https://urldefense.us/v3/__https://github.com/AdvancedPhotonSource/cohere/pull/35.diff__;!!G_uCfscf7eWS!d_iLb1-fcMLjpdmqvCaiyGKhL9H2J14G3eWpiTBg6NAbK1mLqqOKgjpnPKizC1gtPDcjxNcEh_2q0AbluYe-H32fRg$>

**Comment by bfrosik** [comment]
Is the code in lines 174-275 necessary? Seems that the line 148 would do.

**Comment by jacione** [comment]
I think you're referring just to lines 274-275? 

In line 148, `plt.show()` gets called with the argument `block=False`, which allows the main process to continue, but it also closes out the figure as soon as the reconstruction finishes. The call in line 275 blocks the process so that the final frame stays up until you close the figure manually.

**Comment by bfrosik** [comment]
Thanks, good explanation.

**Pull request merged**
