### PR TITLE
Strain from CoupledRec

### PR DESCRIPTION
**Pull request by jacione**
This version calculates the 6-component strain tensor and saves it with the rest of the CoupledRec results. A few other small fixes and improvements.

### CODE REVIEW

**Review by bfrosik — COMMENTED** [review]
1. I like the name changes.
2. The mask file is saved for each peak, if file exist. The usage however is commented out. It seems that it is for verification, to see a plot. So maybe a switch that if true would load the mask file and use it, otherwise not to load it and not use it. Or can the mask be used during the standard preprocess?
3. In get_phase_gradient there are like 25 iterations, executing simple 4-steps. It does not include shrink wrap. Is it intended? It can be also added to the algorithm sequence and then the 25 number of iterations would be settable.
4. There is a modulus function that is commented out. Is there a need for alternate modulus? If so, there is a mechanism to add a new modulus function, and call instead of modulus. The new function mnemonic would be included in algorithm sequence.
5. Functions added to the cplib should be added to cohlib as base, and other libraries, even 'not implemented' if nobody would use torch for example.

**Comment by jacione** [comment]
In response to 2/4: Sorry, I thought I had been working on a different branch and didn't realize those changes got committed to this pull request. A few weeks ago I was trying to implement a "masked modulus" function that would allow some amplitudes to float freely. Since the resampled diffraction pattern doesn't take up the entire array, we're enforcing zeros on points in reciprocal space that likely have measureable (though unmeasured) intensity. The idea was to have something that masked those pixels from the modulus function in reciprocal space to try to prevent Gibb's effects from the abrupt cutoff. I didn't get too far with it.

In response to 3: The idea here was to do some ER iterations on each peak to remove phase artifacts caused by projecting a displacement field onto phase. I'm not sure whether it needs to be user-adjustable. ER stagnates pretty quickly, so more than 25 iterations probably wouldn't gain much, but it's also computationally cheap enough that I suspect it wouldn't provide much extra speed to do fewer.

In response to 5: Yes, I've been bad at doing that, simply because I know very little about other GPU accelerated libraries. The more features I implement, the more I'm also wondering if it's feasible to keep up the interface with so many different backends. I know, for example, that there are functions that exist in some libraries but not others, and there are places where an array attribute is accessed directly (e.g. arr.shape). Trying to maintain consistency between 3-4 different math libraries seems like there are a lot of extra places for bugs to show up. But at the same time, it does increase the software's versatility. Perhaps we can discuss this the next time we meet. In the meantime, however, I will try to be better about implementing things across all libraries.

**Comment by jacione** [comment]
I've added the new cplib methods to the signature of cohlib, and implemented them in nplib. I also added the methods to aflib and torchlib, but only as stubs. I figured I don't know enough about those libraries to do a full implementation, but I can figure it out if you want me to :)

**Comment by jacione** [comment]
I also just got rid of the commented code blocks. They might end up coming back in a future version, but for now I've taken them off the main branch.

**Review by bfrosik — APPROVED** [review]

**Pull request merged**
